apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: diting-infer
data:
  BASE_MODEL: {{ .Values.vllm.baseModelPath | quote }}
  MAX_MODEL_LEN: {{ .Values.vllm.maxModelLen | quote }}
  GPU_MEMORY_UTILIZATION: {{ .Values.vllm.gpuMemoryUtilization | quote }}
