apiVersion: v1
kind: Service
metadata:
  name: diting-infer
  namespace: {{ .Release.Namespace }}
  labels:
    app: diting-infer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: diting-infer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
