---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: diting-akshare-secrets
  namespace: default
spec:
  encryptedData:
    API_KEY: AQAjTM0D9CiUDJFLZ5YAcOOHnlSfSJTqdbfWSH25r5cvbS9NVJY4MMaPxfoc1mw8ZlFW8gIdMrB6B9YBgpV0b9fqpwRFaXK04BrivFmRZMaabREz18IlzsLbM/p7IzzRI34XA3g6x/g8AYxexQfxyCKGxTV7HhMa1P+sTqXL5/9YtXP0XhoRTaTboDz7fD+GqUELv5Cvq9eswogNJT1JnWFjurQzIAEppZFT9x5dxm4MQqEYbj940FBypkEbkVkTT6ZMKkbT7urH3cVJDzxbGgWtmewYG4ZwBSaKAm9/sOI1b4k45mw1WtvxFpi/pUUZwoS/qamlJPtFSh6Bc8eb3OUMnkjam+zE69U7T/H6Lri7OFH90gqRWQJqcL4tGcuuxWEYqgDVAYaGNSg0z+A=
  template:
    metadata:
      name: diting-akshare-secrets
      namespace: default
    type: Opaque
